
package client;

import javax.swing.JOptionPane;

/**
 *
 * @author kvnk1
 */
public class AddBook extends javax.swing.JInternalFrame {

    /** Creates new form AddBook */
    public AddBook() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        bookinformation = new javax.swing.JLabel();
        AddBook = new javax.swing.JPanel();
        id = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        author = new javax.swing.JLabel();
        year = new javax.swing.JLabel();
        isbn = new javax.swing.JLabel();
        edition = new javax.swing.JLabel();
        copies = new javax.swing.JLabel();
        publisher = new javax.swing.JLabel();
        shelf = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        TITLE = new javax.swing.JTextField();
        ISBN = new javax.swing.JTextField();
        AUTHOR = new javax.swing.JTextField();
        PUBLISHER = new javax.swing.JTextField();
        YEAR = new javax.swing.JTextField();
        EDITION = new javax.swing.JTextField();
        COPIES = new javax.swing.JTextField();
        SHELF = new javax.swing.JTextField();
        ADDBOOK = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        available = new javax.swing.JLabel();
        AVAILABLE = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("ADD BOOKS");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Add24.gif"))); // NOI18N

        bookinformation.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bookinformation.setText("BOOK INFORMATION");

        AddBook.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Book", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        id.setText("BOOK ID:");

        title.setText("TITLE:");

        author.setText("AUTHOR(S) :");

        year.setText("YEAR :");

        isbn.setText("ISBN :");

        edition.setText("EDITION :");

        copies.setText("COPIES :");

        publisher.setText("PUBLISHER :");

        shelf.setText("SHELF NO :");

        ADDBOOK.setText("ADD  BOOK");
        ADDBOOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDBOOKActionPerformed(evt);
            }
        });

        available.setText("Available :");

        AVAILABLE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AVAILABLEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddBookLayout = new javax.swing.GroupLayout(AddBook);
        AddBook.setLayout(AddBookLayout);
        AddBookLayout.setHorizontalGroup(
            AddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddBookLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(id)
                    .addComponent(title)
                    .addComponent(author)
                    .addComponent(isbn)
                    .addComponent(year)
                    .addComponent(publisher)
                    .addComponent(copies)
                    .addComponent(available))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ID)
                    .addComponent(TITLE)
                    .addComponent(ISBN)
                    .addComponent(AUTHOR)
                    .addComponent(PUBLISHER)
                    .addGroup(AddBookLayout.createSequentialGroup()
                        .addGroup(AddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AddBookLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel2))
                            .addGroup(AddBookLayout.createSequentialGroup()
                                .addGroup(AddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(AVAILABLE, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(YEAR, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                    .addComponent(COPIES))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(AddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(edition)
                                    .addComponent(shelf))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AddBookLayout.createSequentialGroup()
                                .addComponent(ADDBOOK)
                                .addGap(0, 20, Short.MAX_VALUE))
                            .addComponent(EDITION)
                            .addComponent(SHELF))))
                .addContainerGap())
        );
        AddBookLayout.setVerticalGroup(
            AddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddBookLayout.createSequentialGroup()
                .addGroup(AddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(id)
                    .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title)
                    .addComponent(TITLE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isbn)
                    .addComponent(ISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(author)
                    .addComponent(AUTHOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(publisher)
                    .addComponent(PUBLISHER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(year)
                    .addComponent(YEAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edition)
                    .addComponent(EDITION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(COPIES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(copies)
                    .addComponent(shelf)
                    .addComponent(SHELF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(AddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ADDBOOK)
                        .addComponent(available)
                        .addComponent(AVAILABLE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(bookinformation)
                .addContainerGap(94, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bookinformation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }//GEN-END:initComponents

    private void ADDBOOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDBOOKActionPerformed
        String id=ID.getText();
        String title=TITLE.getText();
        String isbn=ISBN.getText();
        String author=AUTHOR.getText();
        String publisher=PUBLISHER.getText();
        String year=YEAR.getText();
        String edition=EDITION.getText();
        int copies=Integer.parseInt(COPIES.getText());
        String shelf=SHELF.getText();
        String available=AVAILABLE.getText();
        int i = BooksDB.save(id, title, isbn, author, publisher, year, edition, copies, shelf,available);
        if(i>0){
                                        JOptionPane.showMessageDialog(AddBook.this,"Book added successfully!");
                                    ID.setText("");
                                        TITLE.setText("");
                                         ISBN.setText("");
                                    AUTHOR.setText("");
                                    PUBLISHER.setText("");
                                    YEAR.setText("");
                                    EDITION.setText("");
                                    COPIES.setText("");
                                    SHELF.setText("");
                                    AVAILABLE.setText("");
                                        
                                }else{
                                        JOptionPane.showMessageDialog(AddBook.this,"Sorry, unable to save!");
                                }

// TODO add your handling code here:
    }//GEN-LAST:event_ADDBOOKActionPerformed

    private void AVAILABLEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AVAILABLEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AVAILABLEActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADDBOOK;
    private javax.swing.JTextField AUTHOR;
    private javax.swing.JTextField AVAILABLE;
    private javax.swing.JPanel AddBook;
    private javax.swing.JTextField COPIES;
    private javax.swing.JTextField EDITION;
    private javax.swing.JTextField ID;
    private javax.swing.JTextField ISBN;
    private javax.swing.JTextField PUBLISHER;
    private javax.swing.JTextField SHELF;
    private javax.swing.JTextField TITLE;
    private javax.swing.JTextField YEAR;
    private javax.swing.JLabel author;
    private javax.swing.JLabel available;
    private javax.swing.JLabel bookinformation;
    private javax.swing.JLabel copies;
    private javax.swing.JLabel edition;
    private javax.swing.JLabel id;
    private javax.swing.JLabel isbn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel publisher;
    private javax.swing.JLabel shelf;
    private javax.swing.JLabel title;
    private javax.swing.JLabel year;
    // End of variables declaration//GEN-END:variables

}
