
package client;

import javax.swing.JOptionPane;

/**
 *
 * @author kvnk1
 */
public class AddLibrarian extends javax.swing.JInternalFrame {

    /** Creates new form AddLibrarian */
    public AddLibrarian() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        addlibrarian = new javax.swing.JLayeredPane();
        ID = new javax.swing.JLabel();
        PASSWORD = new javax.swing.JLabel();
        NAME = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        register = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Add Librarian");

        addlibrarian.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Librarian", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        ID.setText("ID :");

        PASSWORD.setText("PASSWORD :");

        NAME.setText("NAME :");

        register.setText("Register");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        addlibrarian.setLayer(ID, javax.swing.JLayeredPane.DEFAULT_LAYER);
        addlibrarian.setLayer(PASSWORD, javax.swing.JLayeredPane.DEFAULT_LAYER);
        addlibrarian.setLayer(NAME, javax.swing.JLayeredPane.DEFAULT_LAYER);
        addlibrarian.setLayer(id, javax.swing.JLayeredPane.DEFAULT_LAYER);
        addlibrarian.setLayer(password, javax.swing.JLayeredPane.DEFAULT_LAYER);
        addlibrarian.setLayer(name, javax.swing.JLayeredPane.DEFAULT_LAYER);
        addlibrarian.setLayer(register, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout addlibrarianLayout = new javax.swing.GroupLayout(addlibrarian);
        addlibrarian.setLayout(addlibrarianLayout);
        addlibrarianLayout.setHorizontalGroup(
            addlibrarianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addlibrarianLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addlibrarianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(addlibrarianLayout.createSequentialGroup()
                        .addComponent(ID)
                        .addGap(58, 58, 58)
                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addlibrarianLayout.createSequentialGroup()
                        .addGroup(addlibrarianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PASSWORD)
                            .addComponent(NAME))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addlibrarianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(register)
                            .addGroup(addlibrarianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(password)
                                .addComponent(name)))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        addlibrarianLayout.setVerticalGroup(
            addlibrarianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addlibrarianLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addlibrarianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ID)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addlibrarianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PASSWORD)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addlibrarianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NAME)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(register)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addlibrarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addlibrarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }//GEN-END:initComponents

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
    String ID=id.getText();
    String PASSWORD=password.getText();
    String NAME=name.getText();
        int i = LibrarianDB.save(ID,PASSWORD,NAME);
        if(i>0){
                                        JOptionPane.showMessageDialog(AddLibrarian.this,"Librarian added successfully!");
                                        id.setText("");
                                        password.setText("");
                                         name.setText("");
                                   
                                        
                                }else{
                                        JOptionPane.showMessageDialog(AddLibrarian.this,"Sorry, unable to save!");
                                }
    // TODO add your handling code here:
    }//GEN-LAST:event_registerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ID;
    private javax.swing.JLabel NAME;
    private javax.swing.JLabel PASSWORD;
    private javax.swing.JLayeredPane addlibrarian;
    private javax.swing.JTextField id;
    private javax.swing.JTextField name;
    private javax.swing.JTextField password;
    private javax.swing.JButton register;
    // End of variables declaration//GEN-END:variables

}
