
package client;

import javax.swing.JOptionPane;

/**
 *
 * @author kvnk1
 */
public class AddMember extends javax.swing.JInternalFrame {

    /** Creates new form AddMember */
    public AddMember() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        memberinformation = new javax.swing.JLabel();
        addmember = new javax.swing.JButton();
        ADDMEMBER = new javax.swing.JPanel();
        MEMBERID = new javax.swing.JLabel();
        memberid = new javax.swing.JTextField();
        NAME = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        EMAILID = new javax.swing.JLabel();
        emailid = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        PHONE = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Add Member");

        memberinformation.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        memberinformation.setText("MEMBER INFORMATION");

        addmember.setText("ADD");
        addmember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addmemberActionPerformed(evt);
            }
        });

        ADDMEMBER.setBorder(javax.swing.BorderFactory.createTitledBorder("Add Member"));

        MEMBERID.setText("MEMBER ID:");

        NAME.setText("NAME :");

        EMAILID.setText("EMAIL ID :");

        PHONE.setText("PHONE :");

        javax.swing.GroupLayout ADDMEMBERLayout = new javax.swing.GroupLayout(ADDMEMBER);
        ADDMEMBER.setLayout(ADDMEMBERLayout);
        ADDMEMBERLayout.setHorizontalGroup(
            ADDMEMBERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ADDMEMBERLayout.createSequentialGroup()
                .addGroup(ADDMEMBERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ADDMEMBERLayout.createSequentialGroup()
                        .addGroup(ADDMEMBERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MEMBERID)
                            .addComponent(NAME))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(ADDMEMBERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(memberid, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ADDMEMBERLayout.createSequentialGroup()
                        .addGroup(ADDMEMBERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EMAILID)
                            .addComponent(PHONE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ADDMEMBERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 18, Short.MAX_VALUE))
        );
        ADDMEMBERLayout.setVerticalGroup(
            ADDMEMBERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ADDMEMBERLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ADDMEMBERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MEMBERID)
                    .addComponent(memberid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ADDMEMBERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NAME)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ADDMEMBERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EMAILID)
                    .addComponent(emailid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ADDMEMBERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phone, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(PHONE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(memberinformation))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(addmember)))
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ADDMEMBER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(memberinformation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ADDMEMBER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addmember)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }//GEN-END:initComponents

    private void addmemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addmemberActionPerformed
String Id=memberid.getText();  
        String Name=name.getText();
        String Email=emailid.getText();
        String Phone=phone.getText();
        int i = MembersDB.save(Id,Name,Email,Phone);
        if(i>0){
                                        JOptionPane.showMessageDialog(AddMember.this,"Member added successfully!");
                                    memberid.setText("");
                                        name.setText("");
                                         emailid.setText("");
                                    phone.setText("");
                                        
                                }else{
                                        JOptionPane.showMessageDialog(AddMember.this,"Sorry, unable to save!");
                                }
// TODO add your handling code here:
    }//GEN-LAST:event_addmemberActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ADDMEMBER;
    private javax.swing.JLabel EMAILID;
    private javax.swing.JLabel MEMBERID;
    private javax.swing.JLabel NAME;
    private javax.swing.JLabel PHONE;
    private javax.swing.JButton addmember;
    private javax.swing.JTextField emailid;
    private javax.swing.JTextField memberid;
    private javax.swing.JLabel memberinformation;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phone;
    // End of variables declaration//GEN-END:variables

}
