
package client;

import java.awt.Toolkit;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author kvnk1
 */
public class LibraryManagement extends javax.swing.JFrame {

    /** Creates new form LibraryManagement */
    public LibraryManagement() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        LibraryManagement = new javax.swing.JLabel();
        libraryicon = new javax.swing.JLabel();
        USERID = new javax.swing.JLabel();
        userid = new javax.swing.JTextField();
        PASSWORD = new javax.swing.JLabel();
        librarianlogin = new javax.swing.JButton();
        adminlogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LIBRARY MANAGEMENT");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));

        LibraryManagement.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LibraryManagement.setText("LIBRARY MANAGEMENT");

        libraryicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/library.png"))); // NOI18N

        USERID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        USERID.setForeground(new java.awt.Color(255, 0, 0));
        USERID.setText("USERID");

        PASSWORD.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        PASSWORD.setForeground(new java.awt.Color(255, 0, 0));
        PASSWORD.setText("PASSWORD");

        librarianlogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        librarianlogin.setForeground(new java.awt.Color(0, 0, 204));
        librarianlogin.setText("Librarian Login");
        librarianlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                librarianloginActionPerformed(evt);
            }
        });

        adminlogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        adminlogin.setForeground(new java.awt.Color(0, 0, 204));
        adminlogin.setText("Admin Login");
        adminlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminloginActionPerformed(evt);
            }
        });

        jLabel1.setText("copyright © 2020 all rights reserved");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(libraryicon)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(USERID)
                            .addComponent(PASSWORD)
                            .addComponent(librarianlogin)
                            .addComponent(adminlogin)
                            .addComponent(LibraryManagement)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(password, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                .addComponent(userid, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(libraryicon)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(LibraryManagement)
                        .addGap(28, 28, 28)
                        .addComponent(USERID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PASSWORD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(librarianlogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adminlogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addContainerGap())))
        );

        pack();
    }//GEN-END:initComponents

    private void adminloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminloginActionPerformed
    String id=userid.getText();
    String Password=String.valueOf(password.getPassword());
    
    
                            if(AdminDB.validate(id,Password)){
                                    Admin.main(new String[]{});
                                    dispose();
                            }else{
                                    JOptionPane.showMessageDialog(LibraryManagement.this, "Sorry, UserID or Password Error","Login Error!", JOptionPane.ERROR_MESSAGE);
                                    userid.setText("");
                                    password.setText("");
                            } // TODO add your handling code here:
    }//GEN-LAST:event_adminloginActionPerformed

    private void librarianloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_librarianloginActionPerformed
    String id=userid.getText();
    String Password=String.valueOf(password.getPassword());
                            if(LibrarianDB.validate(id,Password)){
                                    Librarian.main(new String[]{});
                                    dispose();
                            }else{
                                    JOptionPane.showMessageDialog(LibraryManagement.this, "Sorry, UserID or Password Error","Login Error!", JOptionPane.ERROR_MESSAGE);
                                    userid.setText("");
                                    password.setText("");
                            }        // TODO add your handling code here:
    }//GEN-LAST:event_librarianloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing
                                                                   .UIManager
                                                                   .getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing
                         .UIManager
                         .setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util
                .logging
                .Logger
                .getLogger(LibraryManagement.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util
                .logging
                .Logger
                .getLogger(LibraryManagement.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util
                .logging
                .Logger
                .getLogger(LibraryManagement.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util
                .logging
                .Logger
                .getLogger(LibraryManagement.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt
            .EventQueue
            .invokeLater(new Runnable() {
                public void run() {
                    new LibraryManagement().setVisible(true);
                }
            });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LibraryManagement;
    private javax.swing.JLabel PASSWORD;
    private javax.swing.JLabel USERID;
    private javax.swing.JButton adminlogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton librarianlogin;
    private javax.swing.JLabel libraryicon;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField userid;
    // End of variables declaration//GEN-END:variables

}
