
package client;

import java.awt.Toolkit;

/**
 *
 * @author kvnk1
 */
public class Librarian extends javax.swing.JFrame {

    /** Creates new form Librarian */
    public Librarian() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jToolBar1 = new javax.swing.JToolBar();
        specifybooks = new javax.swing.JLabel();
        addbook = new javax.swing.JButton();
        deletebook = new javax.swing.JButton();
        editbook = new javax.swing.JButton();
        bookinfo = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        specifymembers = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        addmembers = new javax.swing.JButton();
        removemembers = new javax.swing.JButton();
        editmembers = new javax.swing.JButton();
        memberinfo = new javax.swing.JButton();
        Loan = new javax.swing.JLabel();
        borrow = new javax.swing.JButton();
        Return = new javax.swing.JButton();
        Search = new javax.swing.JLabel();
        SEARCH = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        HELP = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ABOUT = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        menubar = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        pwdlibrarian = new javax.swing.JMenuItem();
        logout = new javax.swing.JMenuItem();
        books = new javax.swing.JMenu();
        addbooks = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        editbooks = new javax.swing.JMenuItem();
        members = new javax.swing.JMenu();
        addmember = new javax.swing.JMenuItem();
        removemember = new javax.swing.JMenuItem();
        editmember = new javax.swing.JMenuItem();
        loan = new javax.swing.JMenu();
        borrowbook = new javax.swing.JMenuItem();
        returnbook = new javax.swing.JMenuItem();
        reports = new javax.swing.JMenu();
        allbooks = new javax.swing.JMenuItem();
        allmembers = new javax.swing.JMenuItem();
        issuedbooks = new javax.swing.JMenuItem();
        latefees = new javax.swing.JMenuItem();
        search = new javax.swing.JMenu();
        searchbooksandmembers = new javax.swing.JMenuItem();
        help = new javax.swing.JMenu();
        about = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LIBRARY MANAGEMENT");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));

        jToolBar1.setRollover(true);

        specifybooks.setText("Books:");
        jToolBar1.add(specifybooks);

        addbook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Add24.gif"))); // NOI18N
        addbook.setFocusable(false);
        addbook.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addbook.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbookActionPerformed(evt);
            }
        });
        jToolBar1.add(addbook);

        deletebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Delete24.gif"))); // NOI18N
        deletebook.setFocusable(false);
        deletebook.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deletebook.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        deletebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebookActionPerformed(evt);
            }
        });
        jToolBar1.add(deletebook);

        editbook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Edit24.gif"))); // NOI18N
        editbook.setFocusable(false);
        editbook.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editbook.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        editbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbookActionPerformed(evt);
            }
        });
        jToolBar1.add(editbook);

        bookinfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Information24.gif"))); // NOI18N
        bookinfo.setFocusable(false);
        bookinfo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bookinfo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(bookinfo);
        jToolBar1.add(jSeparator1);

        specifymembers.setText("Members:");
        jToolBar1.add(specifymembers);
        jToolBar1.add(jSeparator2);

        addmembers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Add24.gif"))); // NOI18N
        addmembers.setFocusable(false);
        addmembers.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addmembers.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addmembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addmembersActionPerformed(evt);
            }
        });
        jToolBar1.add(addmembers);

        removemembers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Delete24.gif"))); // NOI18N
        removemembers.setFocusable(false);
        removemembers.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        removemembers.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        removemembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removemembersActionPerformed(evt);
            }
        });
        jToolBar1.add(removemembers);

        editmembers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Edit24.gif"))); // NOI18N
        editmembers.setFocusable(false);
        editmembers.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editmembers.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        editmembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editmembersActionPerformed(evt);
            }
        });
        jToolBar1.add(editmembers);

        memberinfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Information24.gif"))); // NOI18N
        memberinfo.setFocusable(false);
        memberinfo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        memberinfo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(memberinfo);

        Loan.setText("  Loan: ");
        jToolBar1.add(Loan);

        borrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Export24.gif"))); // NOI18N
        borrow.setFocusable(false);
        borrow.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        borrow.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        borrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowActionPerformed(evt);
            }
        });
        jToolBar1.add(borrow);

        Return.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Import24.gif"))); // NOI18N
        Return.setFocusable(false);
        Return.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Return.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnActionPerformed(evt);
            }
        });
        jToolBar1.add(Return);

        Search.setText("Search : ");
        jToolBar1.add(Search);

        SEARCH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Find24.gif"))); // NOI18N
        SEARCH.setFocusable(false);
        SEARCH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SEARCH.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        SEARCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEARCHActionPerformed(evt);
            }
        });
        jToolBar1.add(SEARCH);

        jLabel2.setText(" Help :");
        jToolBar1.add(jLabel2);

        HELP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Help24.gif"))); // NOI18N
        HELP.setFocusable(false);
        HELP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        HELP.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(HELP);

        jLabel3.setText("About :");
        jToolBar1.add(jLabel3);

        ABOUT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/About24.gif"))); // NOI18N
        ABOUT.setFocusable(false);
        ABOUT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ABOUT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(ABOUT);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        menubar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        file.setText("FILE");
        file.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        pwdlibrarian.setText("Change Password");
        pwdlibrarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdlibrarianActionPerformed(evt);
            }
        });
        file.add(pwdlibrarian);

        logout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Exit16.gif"))); // NOI18N
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        file.add(logout);

        menubar.add(file);

        books.setText("BOOKS");
        books.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        addbooks.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        addbooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Add24.gif"))); // NOI18N
        addbooks.setText("Add Book");
        addbooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbooksActionPerformed(evt);
            }
        });
        books.add(addbooks);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Delete24.gif"))); // NOI18N
        jMenuItem2.setText("Remove Book");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        books.add(jMenuItem2);

        editbooks.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_MASK));
        editbooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Edit24.gif"))); // NOI18N
        editbooks.setText("Edit Book");
        editbooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbooksActionPerformed(evt);
            }
        });
        books.add(editbooks);

        menubar.add(books);

        members.setText("MEMBERS ");
        members.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        addmember.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        addmember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Add24.gif"))); // NOI18N
        addmember.setText("Add Member");
        addmember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addmemberActionPerformed(evt);
            }
        });
        members.add(addmember);

        removemember.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        removemember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Delete24.gif"))); // NOI18N
        removemember.setText("Remove Member");
        removemember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removememberActionPerformed(evt);
            }
        });
        members.add(removemember);

        editmember.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.SHIFT_MASK));
        editmember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Edit24.gif"))); // NOI18N
        editmember.setText("Edit Member");
        editmember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editmemberActionPerformed(evt);
            }
        });
        members.add(editmember);

        menubar.add(members);

        loan.setText("LOAN ");
        loan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        borrowbook.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        borrowbook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Export24.gif"))); // NOI18N
        borrowbook.setText("Borrow Book");
        borrowbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowbookActionPerformed(evt);
            }
        });
        loan.add(borrowbook);

        returnbook.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        returnbook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Import24.gif"))); // NOI18N
        returnbook.setText("Return Book");
        returnbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnbookActionPerformed(evt);
            }
        });
        loan.add(returnbook);

        menubar.add(loan);

        reports.setText("REPORTS ");
        reports.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        allbooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/List24.gif"))); // NOI18N
        allbooks.setText("All Books");
        allbooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allbooksActionPerformed(evt);
            }
        });
        reports.add(allbooks);

        allmembers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/List24.gif"))); // NOI18N
        allmembers.setText("All Members");
        allmembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allmembersActionPerformed(evt);
            }
        });
        reports.add(allmembers);

        issuedbooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/List24.gif"))); // NOI18N
        issuedbooks.setText("Issued Books");
        issuedbooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issuedbooksActionPerformed(evt);
            }
        });
        reports.add(issuedbooks);

        latefees.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/List24.gif"))); // NOI18N
        latefees.setText("Late Fees");
        latefees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                latefeesActionPerformed(evt);
            }
        });
        reports.add(latefees);

        menubar.add(reports);

        search.setText("SEARCH");
        search.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        searchbooksandmembers.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        searchbooksandmembers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Find16.gif"))); // NOI18N
        searchbooksandmembers.setText("Search");
        searchbooksandmembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbooksandmembersActionPerformed(evt);
            }
        });
        search.add(searchbooksandmembers);

        menubar.add(search);

        help.setText(" HELP ");
        help.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menubar.add(help);

        about.setText("ABOUT");
        about.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menubar.add(about);

        setJMenuBar(menubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1320, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        pack();
    }//GEN-END:initComponents

    private void addmemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addmemberActionPerformed
    AddMember frame = new AddMember();  
        frame.setVisible(true);  
        jDesktopPane1.add(frame);  
        try  
        {  
            frame.setSelected(true);  
        } catch (java.beans.PropertyVetoException e)  
        {  
            System.out.println(e);  
        }        // TODO add your handling code here:
    }//GEN-LAST:event_addmemberActionPerformed

    private void removememberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removememberActionPerformed
    RemoveMember frame = new RemoveMember();  
        frame.setVisible(true);  
        jDesktopPane1.add(frame);  
        try  
        {  
            frame.setSelected(true);  
        } catch (java.beans.PropertyVetoException e)  
        {  
            System.out.println(e);  
        }     // TODO add your handling code here:
    }//GEN-LAST:event_removememberActionPerformed

    private void allbooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allbooksActionPerformed
    ListAllBooks frame = new ListAllBooks();  
        frame.setVisible(true);  
        jDesktopPane1.add(frame);  
        try  
        {  
            frame.setSelected(true);  
        } catch (java.beans.PropertyVetoException e)  
        {  
            System.out.println(e);  
        } 
                  // TODO add your handling code here:
    }//GEN-LAST:event_allbooksActionPerformed

    private void issuedbooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issuedbooksActionPerformed
    ListIssuedBooks frame = new ListIssuedBooks();  
        frame.setVisible(true);  
        jDesktopPane1.add(frame);  
        try  
        {  
            frame.setSelected(true);  
        } catch (java.beans.PropertyVetoException e)  
        {  
            System.out.println(e);  
        }     // TODO add your handling code here:
    }//GEN-LAST:event_issuedbooksActionPerformed

    private void allmembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allmembersActionPerformed
    ListAllMembers frame = new ListAllMembers();  
        frame.setVisible(true);  
        jDesktopPane1.add(frame);  
        try  
        {  
            frame.setSelected(true);  
        } catch (java.beans.PropertyVetoException e)  
        {  
            System.out.println(e);  
        }    // TODO add your handling code here:
    }//GEN-LAST:event_allmembersActionPerformed

    private void addbooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbooksActionPerformed
    AddBook frame = new AddBook();  
        frame.setVisible(true);  
        jDesktopPane1.add(frame);  
        try  
        {  
            frame.setSelected(true);  
        } catch (java.beans.PropertyVetoException e)  
        {  
            System.out.println(e);  
        } 
                               // TODO add your handling code here:
    }//GEN-LAST:event_addbooksActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
    LibraryManagement.main(new String[]{});
     dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    private void editbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbookActionPerformed
    EditBook frame = new EditBook();  
        frame.setVisible(true);  
        jDesktopPane1.add(frame);  
        try  
        {  
            frame.setSelected(true);  
        } catch (java.beans.PropertyVetoException e)  
        {  
            System.out.println(e);  
        }        // TODO add your handling code here:
    }//GEN-LAST:event_editbookActionPerformed

    private void addbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbookActionPerformed
    AddBook frame = new AddBook();  
        frame.setVisible(true);  
        jDesktopPane1.add(frame);  
        try  
        {  
            frame.setSelected(true);  
        } catch (java.beans.PropertyVetoException e)  
        {  
            System.out.println(e);  
        }         // TODO add your handling code here:
    }//GEN-LAST:event_addbookActionPerformed

    private void deletebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebookActionPerformed
    RemoveBook frame = new RemoveBook();  
        frame.setVisible(true);  
        jDesktopPane1.add(frame);  
        try  
        {  
            frame.setSelected(true);  
        } catch (java.beans.PropertyVetoException e)  
        {  
            System.out.println(e);  
        } // TODO add your handling code here:
    }//GEN-LAST:event_deletebookActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
    RemoveBook frame = new RemoveBook();  
        frame.setVisible(true);  
        jDesktopPane1.add(frame);  
        try  
        {  
            frame.setSelected(true);  
        } catch (java.beans.PropertyVetoException e)  
        {  
            System.out.println(e);  
        }   // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void editbooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbooksActionPerformed
        EditBook frame = new EditBook();  
            frame.setVisible(true);  
            jDesktopPane1.add(frame);  
            try  
            {  
                frame.setSelected(true);  
            } catch (java.beans.PropertyVetoException e)  
            {  
                System.out.println(e);  
            }// TODO add your handling code here:
    }//GEN-LAST:event_editbooksActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void SEARCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEARCHActionPerformed
    SearchBooksAndMembers frame = new SearchBooksAndMembers();  
        frame.setVisible(true);  
        jDesktopPane1.add(frame);  
        try  
        {  
            frame.setSelected(true);  
        } catch (java.beans.PropertyVetoException e)  
        {  
            System.out.println(e);  
        }        // TODO add your handling code here:
    }//GEN-LAST:event_SEARCHActionPerformed

    private void searchbooksandmembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbooksandmembersActionPerformed
    SearchBooksAndMembers frame = new SearchBooksAndMembers();  
        frame.setVisible(true);  
        jDesktopPane1.add(frame);  
        try  
        {  
            frame.setSelected(true);  
        } catch (java.beans.PropertyVetoException e)  
        {  
            System.out.println(e);  
        }        // TODO add your handling code here:
    }//GEN-LAST:event_searchbooksandmembersActionPerformed

    private void addmembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addmembersActionPerformed
    AddMember frame = new AddMember();  
        frame.setVisible(true);  
        jDesktopPane1.add(frame);  
        try  
        {  
            frame.setSelected(true);  
        } catch (java.beans.PropertyVetoException e)  
        {  
            System.out.println(e);  
        }        // TODO add your handling code here:
    }//GEN-LAST:event_addmembersActionPerformed

    private void removemembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removemembersActionPerformed
    RemoveMember frame = new RemoveMember();  
        frame.setVisible(true);  
        jDesktopPane1.add(frame);  
        try  
        {  
            frame.setSelected(true);  
        } catch (java.beans.PropertyVetoException e)  
        {  
            System.out.println(e);  
        }         // TODO add your handling code here:
    }//GEN-LAST:event_removemembersActionPerformed

    private void editmemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editmemberActionPerformed
    EditMember frame = new EditMember();  
        frame.setVisible(true);  
        jDesktopPane1.add(frame);  
        try  
        {  
            frame.setSelected(true);  
        } catch (java.beans.PropertyVetoException e)  
        {  
            System.out.println(e); } 
         // TODO add your handling code here:
    }//GEN-LAST:event_editmemberActionPerformed

    private void editmembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editmembersActionPerformed
    EditMember frame = new EditMember();  
        frame.setVisible(true);  
        jDesktopPane1.add(frame);  
        try  
        {  
            frame.setSelected(true);  
        } catch (java.beans.PropertyVetoException e)  
        {  
            System.out.println(e); }         // TODO add your handling code here:
    }//GEN-LAST:event_editmembersActionPerformed

    private void borrowbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowbookActionPerformed
    Borrow frame = new Borrow();  
        frame.setVisible(true);  
        jDesktopPane1.add(frame);  
        try  
        {  
            frame.setSelected(true);  
        } catch (java.beans.PropertyVetoException e)  
        {  
            System.out.println(e); }       // TODO add your handling code here:
    }//GEN-LAST:event_borrowbookActionPerformed

    private void borrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowActionPerformed
    Borrow frame = new Borrow();  
        frame.setVisible(true);  
        jDesktopPane1.add(frame);  
        try  
        {  
            frame.setSelected(true);  
        } catch (java.beans.PropertyVetoException e)  
        {  
            System.out.println(e); }        // TODO add your handling code here:
    }//GEN-LAST:event_borrowActionPerformed

    private void latefeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_latefeesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_latefeesActionPerformed

    private void returnbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnbookActionPerformed
    Return frame = new Return();  
        frame.setVisible(true);  
        jDesktopPane1.add(frame);  
        try  
        {  
            frame.setSelected(true);  
        } catch (java.beans.PropertyVetoException e)  
        {  
            System.out.println(e); }    // TODO add your handling code here:
    }//GEN-LAST:event_returnbookActionPerformed

    private void ReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnActionPerformed
    Return frame = new Return();  
        frame.setVisible(true);  
        jDesktopPane1.add(frame);  
        try  
        {  
            frame.setSelected(true);  
        } catch (java.beans.PropertyVetoException e)  
        {  
            System.out.println(e); }      // TODO add your handling code here:
    }//GEN-LAST:event_ReturnActionPerformed

    private void pwdlibrarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdlibrarianActionPerformed
    ChangePwdLibrarian frame = new ChangePwdLibrarian();  
        frame.setVisible(true);  
        jDesktopPane1.add(frame);  
        try  
        {  
            frame.setSelected(true);  
        } catch (java.beans.PropertyVetoException e)  
        {  
            System.out.println(e); }    // TODO add your handling code here:
    }//GEN-LAST:event_pwdlibrarianActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing
                                                                   .UIManager
                                                                   .getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing
                         .UIManager
                         .setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util
                .logging
                .Logger
                .getLogger(Librarian.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util
                .logging
                .Logger
                .getLogger(Librarian.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util
                .logging
                .Logger
                .getLogger(Librarian.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util
                .logging
                .Logger
                .getLogger(Librarian.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt
            .EventQueue
            .invokeLater(new Runnable() {
                public void run() {
                    new Librarian().setVisible(true);
                }
            });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ABOUT;
    private javax.swing.JButton HELP;
    private javax.swing.JLabel Loan;
    private javax.swing.JButton Return;
    private javax.swing.JButton SEARCH;
    private javax.swing.JLabel Search;
    private javax.swing.JMenu about;
    private javax.swing.JButton addbook;
    private javax.swing.JMenuItem addbooks;
    private javax.swing.JMenuItem addmember;
    private javax.swing.JButton addmembers;
    private javax.swing.JMenuItem allbooks;
    private javax.swing.JMenuItem allmembers;
    private javax.swing.JButton bookinfo;
    private javax.swing.JMenu books;
    private javax.swing.JButton borrow;
    private javax.swing.JMenuItem borrowbook;
    private javax.swing.JButton deletebook;
    private javax.swing.JButton editbook;
    private javax.swing.JMenuItem editbooks;
    private javax.swing.JMenuItem editmember;
    private javax.swing.JButton editmembers;
    private javax.swing.JMenu file;
    private javax.swing.JMenu help;
    private javax.swing.JMenuItem issuedbooks;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem latefees;
    private javax.swing.JMenu loan;
    private javax.swing.JMenuItem logout;
    private javax.swing.JButton memberinfo;
    private javax.swing.JMenu members;
    private javax.swing.JMenuBar menubar;
    private javax.swing.JMenuItem pwdlibrarian;
    private javax.swing.JMenuItem removemember;
    private javax.swing.JButton removemembers;
    private javax.swing.JMenu reports;
    private javax.swing.JMenuItem returnbook;
    private javax.swing.JMenu search;
    private javax.swing.JMenuItem searchbooksandmembers;
    private javax.swing.JLabel specifybooks;
    private javax.swing.JLabel specifymembers;
    // End of variables declaration//GEN-END:variables

}
