
package client;

import java.awt.print.PrinterException;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

import java.text.MessageFormat;

import java.util.ArrayList;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kvnk1
 */
public class ListAllLibrarians extends javax.swing.JInternalFrame {

    /** Creates new form ListAllLibrarians */
    public ListAllLibrarians() {
        initComponents();
        show_librarian();
    }
    public ArrayList<Librarians> librarianList(){
        ArrayList<Librarians> librariansList=new ArrayList<>();
            try{
                    Class.forName("oracle.jdbc.driver.OracleDriver");
                  Connection  con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","manager");
                     con=DB.getConnection();
                   Statement st=con.createStatement();
                ResultSet rs=st.executeQuery("select*from librarian");
                Librarians librarian;
                while(rs.next()){
                    librarian=new Librarians(rs.getString("id"),rs.getString("password"),rs.getString("name"));
                    librariansList.add(librarian);
                    }
            }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
                }
            return librariansList;
        }
    public void show_librarian(){
        ArrayList<Librarians> list= librarianList();
        DefaultTableModel model = (DefaultTableModel) listalllibrarians.getModel();
        Object[] row= new Object[10];
        for(int i=0;i<list.size();i++){
            row[0]=list.get(i).getid();
            row[1]=list.get(i).getpassword();
                row[2]=list.get(i).getname();
                
                 model.addRow(row);
            }}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listalllibrarians = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("List All Librarians");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Print24.gif"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        listalllibrarians.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "PASSWORD", "NAME"
            }
        ));
        jScrollPane1.setViewportView(listalllibrarians);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(177, 177, 177))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    MessageFormat header = new MessageFormat("Print Report");
            MessageFormat footer = new MessageFormat("Page{0,number,integer}");
        try {
            listalllibrarians.print();
        } catch (java.awt.print.PrinterAbortException e) {
            
        } catch (PrinterException ex) {
            Logger.getLogger(ListAllLibrarians.class.getName()).log(Level.SEVERE, null, ex);
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listalllibrarians;
    // End of variables declaration//GEN-END:variables

}
