
package client;

import java.awt.Cursor;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;

import java.sql.Connection;
import java.sql.DriverManager;

import java.sql.ResultSet;
import java.sql.Statement;

import java.text.MessageFormat;

import java.util.ArrayList;

import java.util.logging.*;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kvnk1
 */
public class ListAllBooks extends javax.swing.JInternalFrame {

    /** Creates new form ListAllBooks */
    public ListAllBooks() {
        initComponents();
        show_book();
    }
    public ArrayList<Book> bookList(){
        ArrayList<Book> booksList=new ArrayList<>();
            try{
                    Class.forName("oracle.jdbc.driver.OracleDriver");
                  Connection  con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","manager");
                     con=DB.getConnection();
                   Statement st=con.createStatement();
                ResultSet rs=st.executeQuery("select*from books");
                Book book;
                while(rs.next()){
                    book=new Book(rs.getString("id"),rs.getString("title"),rs.getString("isbn"),rs.getString("author"),rs.getString("publisher"),rs.getString("year"),rs.getString("edition"),rs.getInt("copies"),rs.getString("shelf"),rs.getString("available"));
                    booksList.add(book);
                    }
            }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
                }
            return booksList;
        }
    public void show_book(){
        ArrayList<Book> list= bookList();
        DefaultTableModel model = (DefaultTableModel) listallbooks.getModel();
        Object[] row= new Object[10];
        for(int i=0;i<list.size();i++){
            row[0]=list.get(i).getid();
            row[1]=list.get(i).gettitle();
                row[2]=list.get(i).getisbn();
                row[3]=list.get(i).getauthor();
                row[4]=list.get(i).getpublisher();
                row[5]=list.get(i).getyear();
                row[6]=list.get(i).getedition();
                row[7]=list.get(i).getcopies();
                row[8]=list.get(i).getshelf();
                row[9]=list.get(i).getavailable();
                 model.addRow(row);
            }
        }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jScrollPane1 = new javax.swing.JScrollPane();
        listallbooks = new javax.swing.JTable();
        printallbooks = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("List All Books");

        listallbooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "TITLE", "ISBN", "AUTHOR", "PUBLISHER", "YEAR", "EDITION", "COPIES", "SHELF", "AVAILABLE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(listallbooks);

        printallbooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Print24.gif"))); // NOI18N
        printallbooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printallbooksActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1242, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(604, 604, 604)
                .addComponent(printallbooks)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(printallbooks)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }//GEN-END:initComponents

    private void printallbooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printallbooksActionPerformed
    MessageFormat header = new MessageFormat("Print Report");
            MessageFormat footer = new MessageFormat("Page{0,number,integer}");
        try {
            listallbooks.print();
        } catch (java.awt.print.PrinterAbortException e) {
            
        } catch (PrinterException ex) {
            Logger.getLogger(ListAllBooks.class.getName()).log(Level.SEVERE, null, ex);
        }          // TODO add your handling code here:
    }//GEN-LAST:event_printallbooksActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listallbooks;
    private javax.swing.JButton printallbooks;
    // End of variables declaration//GEN-END:variables

}
