
package client;

import java.awt.print.PrinterException;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

import java.text.MessageFormat;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kvnk1
 */
public class ListIssuedBooks extends javax.swing.JInternalFrame {

    /** Creates new form ListIssuedBooks */
    public ListIssuedBooks() {
        initComponents();
        show_issued();
    }
    public ArrayList<Issued> issuedList(){
        ArrayList<Issued> issuedlists=new ArrayList<>();
            try{
                    Class.forName("oracle.jdbc.driver.OracleDriver");
                  Connection  con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","manager");
                     con=DB.getConnection();
                   Statement st=con.createStatement();
                ResultSet rs=st.executeQuery("select*from borrow");
                Member member;
                while(rs.next()){
                Issued issued =
                    new Issued(rs.getString("bookid"), rs.getString("memberid"), rs.getString("currentdate"),
                               rs.getString("returndate"));
                issuedlists.add(issued);
                    }
            }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
                }
            return issuedlists;
        }
    public void show_issued(){
        ArrayList<Issued> list= issuedList();
        DefaultTableModel model = (DefaultTableModel) listissuedbooks.getModel();
        Object[] row= new Object[10];
        for(int i=0;i<list.size();i++){
            row[0]=list.get(i).getbookid();
            row[1]=list.get(i).getmemberid();
                row[2]=list.get(i).getcurrentdate();
                row[3]=list.get(i).getreturndate();
                
                 model.addRow(row);
            }}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jScrollPane1 = new javax.swing.JScrollPane();
        listissuedbooks = new javax.swing.JTable();
        printissuedbooks = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("List Of Issued Books");

        listissuedbooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book ID", "Member ID", "Borrow Date", "Return Date"
            }
        ));
        jScrollPane1.setViewportView(listissuedbooks);

        printissuedbooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Print24.gif"))); // NOI18N
        printissuedbooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printissuedbooksActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(printissuedbooks)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(printissuedbooks)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }//GEN-END:initComponents

    private void printissuedbooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printissuedbooksActionPerformed
    MessageFormat header = new MessageFormat("Print Report");
            MessageFormat footer = new MessageFormat("Page{0,number,integer}");
        try {
            listissuedbooks.print();
        } catch (java.awt.print.PrinterAbortException e) {
            
        } catch (PrinterException ex) {
            Logger.getLogger(ListIssuedBooks.class.getName()).log(Level.SEVERE, null, ex);
        }         // TODO add your handling code here:
    }//GEN-LAST:event_printissuedbooksActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listissuedbooks;
    private javax.swing.JButton printissuedbooks;
    // End of variables declaration//GEN-END:variables

}
