
package client;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import java.text.ParseException;
import java.text.SimpleDateFormat;

import java.time.LocalDate;

import java.time.ZoneId;

import java.util.ArrayList;

import java.util.Date;

import java.util.Locale;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author kvnk1
 */
public class Return extends javax.swing.JInternalFrame {

    /** Creates new form Return */
    public Return() {
        initComponents();
        
    }
    public ArrayList<Issued> issuedList(){
        ArrayList<Issued> issuedlists=new ArrayList<>();
            try{
                    Class.forName("oracle.jdbc.driver.OracleDriver");
                  Connection  con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","manager");
                     con=DB.getConnection();
                   Statement st=con.createStatement();
                ResultSet rs=st.executeQuery("select *from borrow where bookid='"+bookid.getText()+"' and memberid='"+memberid.getText()+"'");
                Member member;
                while(rs.next()){
                Issued issued =
                    new Issued(rs.getString("bookid"), rs.getString("memberid"), rs.getString("currentdate"),
                               rs.getString("returndate"));
                issuedlists.add(issued);
                    }
            }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
                }
            return issuedlists;
        }
    public void show_issued(){
        ArrayList<Issued> list= issuedList();
        DefaultTableModel model = (DefaultTableModel) ReturnBook.getModel();
                model.getDataVector().removeAllElements();
                model.fireTableDataChanged();
        Object[] row= new Object[10];
        for(int i=0;i<list.size();i++){
            row[0]=list.get(i).getbookid();
            row[1]=list.get(i).getmemberid();
                row[2]=list.get(i).getcurrentdate();
                row[3]=list.get(i).getreturndate();
                 model.addRow(row);
            }}
    public void executeSQLQuery(String query,String message){
        try{
        Connection  con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","manager");
         con=DB.getConnection();
        Statement st;
        
            st=con.createStatement();
            if(st.executeUpdate(query)==1){
                DefaultTableModel model = (DefaultTableModel) ReturnBook.getModel();
                model.setRowCount(0);
                show_issued();
                JOptionPane.showMessageDialog(null, "Book "+message+"successfully");
                bookid.setText("");
                memberid.setText("");
                borrowdate.setText("");
                returndate.setText("");
                days.setText("");
                
            }else{
                    JOptionPane.showMessageDialog(null, "Book Not "+message);
                }
            } catch (SQLException e) {
            e.printStackTrace();
        }}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        returnbook = new javax.swing.JPanel();
        Bookid = new javax.swing.JLabel();
        Memberid = new javax.swing.JLabel();
        GetDetails = new javax.swing.JButton();
        bookid = new javax.swing.JTextField();
        memberid = new javax.swing.JTextField();
        returnBook = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        borrowdate = new javax.swing.JTextField();
        returndate = new javax.swing.JTextField();
        BOOROWDATE = new javax.swing.JLabel();
        RETURNDATE = new javax.swing.JLabel();
        DayS = new javax.swing.JLabel();
        days = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ReturnBook = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Return Book");

        returnbook.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Return Book", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        Bookid.setText("BOOK ID:");

        Memberid.setText("Member ID:");

        GetDetails.setText("Get Details");
        GetDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout returnbookLayout = new javax.swing.GroupLayout(returnbook);
        returnbook.setLayout(returnbookLayout);
        returnbookLayout.setHorizontalGroup(
            returnbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnbookLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(returnbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bookid)
                    .addComponent(Memberid))
                .addGap(22, 22, 22)
                .addGroup(returnbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GetDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(returnbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(memberid, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                        .addComponent(bookid)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        returnbookLayout.setVerticalGroup(
            returnbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnbookLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(returnbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bookid)
                    .addComponent(bookid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(returnbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Memberid)
                    .addComponent(memberid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(GetDetails))
        );

        returnBook.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        returnBook.setText("RETURN BOOK");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Late Fee Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        BOOROWDATE.setText("BORROW DATE :");

        RETURNDATE.setText("RETURN DATE :");

        DayS.setText("No of Late Days :");

        jButton1.setText("Return Book");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BOOROWDATE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(borrowdate, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(RETURNDATE)
                                .addGap(50, 50, 50))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(DayS)
                                .addGap(42, 42, 42)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(returndate, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(days))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(borrowdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BOOROWDATE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(returndate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RETURNDATE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DayS)
                    .addComponent(days, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        ReturnBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BOOK ID", "MEMBER ID", "BORROW DATE", "RETURN DATE"
            }
        ));
        ReturnBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReturnBookMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ReturnBook);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(returnBook))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(returnbook, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(returnBook)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(returnbook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }//GEN-END:initComponents

    private void GetDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetDetailsActionPerformed
show_issued();        // TODO add your handling code here:
    }//GEN-LAST:event_GetDetailsActionPerformed

    private void ReturnBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReturnBookMouseClicked
    int i=ReturnBook.getSelectedRow();
    TableModel model=ReturnBook.getModel();
    borrowdate.setText(model.getValueAt(i,2).toString());
    returndate.setText(model.getValueAt(i,3).toString());
    String Returndate=returndate.getText();
    LocalDate today = LocalDate.now();
        String date = new SimpleDateFormat("dd/MM/yy", Locale.getDefault()).format(new java.util.Date());
        SimpleDateFormat myFormat = new SimpleDateFormat("dd/MM/yyyy");
        try {
            Date ReturnDate = myFormat.parse(Returndate);
            Date CurrentDate=myFormat.parse(date);
            long difference = ((CurrentDate.getTime()-ReturnDate.getTime())/(1000 * 60 * 60 * 24));
            if(difference<0){
                days.setText("0");
                }
            else{
            String Days = String.valueOf(difference);
            days.setText(Days);
            }
        } catch (ParseException e) {
            e.printStackTrace();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_ReturnBookMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String query="delete from borrow where bookid='"+bookid.getText()+"' and memberid='"+memberid.getText()+"' and currentdate='"+borrowdate.getText()+"' and returndate='"+returndate.getText()+"'";
        executeSQLQuery(query," Returned "); 
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BOOROWDATE;
    private javax.swing.JLabel Bookid;
    private javax.swing.JLabel DayS;
    private javax.swing.JButton GetDetails;
    private javax.swing.JLabel Memberid;
    private javax.swing.JLabel RETURNDATE;
    private javax.swing.JTable ReturnBook;
    private javax.swing.JTextField bookid;
    private javax.swing.JTextField borrowdate;
    private javax.swing.JTextField days;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField memberid;
    private javax.swing.JLabel returnBook;
    private javax.swing.JPanel returnbook;
    private javax.swing.JTextField returndate;
    // End of variables declaration//GEN-END:variables

}
