
package client;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kvnk1
 */
public class SearchBooksAndMembers extends javax.swing.JInternalFrame {

    /** Creates new form SearchBooksAndMembers */
    public SearchBooksAndMembers() {
        initComponents();
      
    }
    public ArrayList<Book> bookList(){
        ArrayList<Book> booksList=new ArrayList<>();
            try{
                    Class.forName("oracle.jdbc.driver.OracleDriver");
                  Connection  con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","manager");
                     con=DB.getConnection();
                   Statement st=con.createStatement();
                ResultSet rs=st.executeQuery("select*from books where id='"+searchforbook.getText()+"' or isbn='"+searchforbook.getText()+"' or author='"+searchforbook.getText()+"' or title='"+searchforbook.getText()+"' or publisher='"+searchforbook.getText()+"' ");
                Book book;
                while(rs.next()){
                    book=new Book(rs.getString("id"),rs.getString("title"),rs.getString("isbn"),rs.getString("author"),rs.getString("publisher"),rs.getString("year"),rs.getString("edition"),rs.getInt("copies"),rs.getString("shelf"),rs.getString("available"));
                    booksList.add(book);
                    }
            }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
                }
            return booksList;
        }
    public void show_book(){
        ArrayList<Book> list= bookList();
        DefaultTableModel model = (DefaultTableModel) SearchBook.getModel();
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
        Object[] row= new Object[10];
        for(int i=0;i<list.size();i++){
            row[0]=list.get(i).getid();
            row[1]=list.get(i).gettitle();
                row[2]=list.get(i).getisbn();
                row[3]=list.get(i).getauthor();
                row[4]=list.get(i).getpublisher();
                row[5]=list.get(i).getyear();
                row[6]=list.get(i).getedition();
                row[7]=list.get(i).getcopies();
                row[8]=list.get(i).getshelf();
                row[9]=list.get(i).getavailable();
                 model.addRow(row);
            }
        }
    public ArrayList<Member> memberList(){
        ArrayList<Member> membersList=new ArrayList<>();
            try{
                    Class.forName("oracle.jdbc.driver.OracleDriver");
                  Connection  con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","manager");
                     con=DB.getConnection();
                   Statement st=con.createStatement();
                ResultSet rs=st.executeQuery("select*from members where id='"+searchformember.getText()+"' or name='"+searchformember.getText()+"' or email='"+searchformember.getText()+"' or phone='"+searchformember.getText()+"' ");
                Member member;
                while(rs.next()){
                    member=new Member(rs.getString("id"),rs.getString("name"),rs.getString("email"),rs.getString("phone"));
                    membersList.add(member);
                    }
            }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
                }
            return membersList;
        }
    public void show_member(){
        ArrayList<Member> list= memberList();
        DefaultTableModel model = (DefaultTableModel) SearchMember.getModel();
                model.getDataVector().removeAllElements();
                model.fireTableDataChanged();
        Object[] row= new Object[10];
        for(int i=0;i<list.size();i++){
            row[0]=list.get(i).getid();
            row[1]=list.get(i).getname();
                row[2]=list.get(i).getemail();
                row[3]=list.get(i).getphone();
                
                 model.addRow(row);
            }}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        search = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        keyword = new javax.swing.JLabel();
        searchforbook = new javax.swing.JTextField();
        SEARCHFORBOOK = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        SearchBook = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        KEYWORD = new javax.swing.JLabel();
        searchformember = new javax.swing.JTextField();
        SEARCHFORMEMBER = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        SearchMember = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Search");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Find24.gif"))); // NOI18N

        search.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        search.setText("Search of Books and Members");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search for Book", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        keyword.setText("Write the Key Word :");

        SEARCHFORBOOK.setText("Search");
        SEARCHFORBOOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEARCHFORBOOKActionPerformed(evt);
            }
        });

        SearchBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Title", "ISBN", "AUTHOR(S)", "PUBLISHER", "YEAR", "EDITION", "COPIES", "SHELF", "AVAILABLE"
            }
        ));
        jScrollPane1.setViewportView(SearchBook);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(keyword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchforbook, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(SEARCHFORBOOK)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keyword)
                    .addComponent(searchforbook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SEARCHFORBOOK))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search for Member", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        KEYWORD.setText("Write the Key Word :");

        SEARCHFORMEMBER.setText("Search");
        SEARCHFORMEMBER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEARCHFORMEMBERActionPerformed(evt);
            }
        });

        SearchMember.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "EMAIL", "PHONE"
            }
        ));
        jScrollPane2.setViewportView(SearchMember);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(KEYWORD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchformember, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(SEARCHFORMEMBER)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KEYWORD)
                    .addComponent(searchformember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SEARCHFORMEMBER))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addComponent(search)
                .addContainerGap(262, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }//GEN-END:initComponents

    private void SEARCHFORBOOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEARCHFORBOOKActionPerformed
    show_book();          // TODO add your handling code here:
    }//GEN-LAST:event_SEARCHFORBOOKActionPerformed

    private void SEARCHFORMEMBERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEARCHFORMEMBERActionPerformed
  show_member();        // TODO add your handling code here:
    }//GEN-LAST:event_SEARCHFORMEMBERActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel KEYWORD;
    private javax.swing.JButton SEARCHFORBOOK;
    private javax.swing.JButton SEARCHFORMEMBER;
    private javax.swing.JTable SearchBook;
    private javax.swing.JTable SearchMember;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel keyword;
    private javax.swing.JLabel search;
    private javax.swing.JTextField searchforbook;
    private javax.swing.JTextField searchformember;
    // End of variables declaration//GEN-END:variables

}
